# Generated by Codex on 2026-06-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CopilotConversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copilotconversation_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copilotconversation_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copilot_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_copilot_conversations",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Copilot Conversation",
                "verbose_name_plural": "Copilot Conversations",
                "db_table": "copilot_conversations",
                "ordering": ("-last_message_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="CopilotMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
                ),
                ("mode", models.CharField(max_length=30)),
                ("prompt", models.TextField()),
                ("answer", models.TextField(blank=True, default="")),
                ("citations", models.JSONField(blank=True, default=list)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("action_results", models.JSONField(blank=True, default=list)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="db.copilotconversation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copilotmessage_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_copilot_messages",
                        to="db.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_copilot_messages",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copilotmessage_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copilot_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_copilot_messages",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Copilot Message",
                "verbose_name_plural": "Copilot Messages",
                "db_table": "copilot_messages",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="copilotconversation",
            index=models.Index(fields=["workspace", "user", "-last_message_at"], name="copilot_conv_ws_user_idx"),
        ),
        migrations.AddIndex(
            model_name="copilotmessage",
            index=models.Index(fields=["conversation", "created_at"], name="copilot_msg_conversation_idx"),
        ),
        migrations.AddIndex(
            model_name="copilotmessage",
            index=models.Index(fields=["workspace", "user", "created_at"], name="copilot_msg_workspace_user_idx"),
        ),
    ]
