# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0122_copilotconversation_copilotmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimate",
            name="type",
            field=models.CharField(
                choices=[("categories", "Categories"), ("points", "Points"), ("time", "Time")],
                default="categories",
                max_length=255,
            ),
        ),
    ]
