# Generated by Django 4.2.30 on 2026-06-06 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.copilot


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_alter_estimate_type_self_host_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copilotconversation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='copilotconversation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='copilotmessage',
            name='action_results',
            field=models.JSONField(blank=True, default=plane.db.models.copilot.empty_list),
        ),
        migrations.AlterField(
            model_name='copilotmessage',
            name='actions',
            field=models.JSONField(blank=True, default=plane.db.models.copilot.empty_list),
        ),
        migrations.AlterField(
            model_name='copilotmessage',
            name='citations',
            field=models.JSONField(blank=True, default=plane.db.models.copilot.empty_list),
        ),
        migrations.AlterField(
            model_name='copilotmessage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='copilotmessage',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
    ]
