# Generated by Django 5.2.15 on 2026-06-14 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_work_item_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringWorkItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=20)),
                ('rrule', models.CharField(blank=True, max_length=512, null=True)),
                ('timezone', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_iterations', models.PositiveIntegerField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_recurring_work_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_work_items', to='db.workitemtemplate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Recurring Work Item',
                'verbose_name_plural': 'Recurring Work Items',
                'db_table': 'recurring_work_items',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecurringWorkItemRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('run_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('generated_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_runs', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('recurring_work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='db.recurringworkitem')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Recurring Work Item Run',
                'verbose_name_plural': 'Recurring Work Item Runs',
                'db_table': 'recurring_work_item_runs',
                'ordering': ('-run_at',),
            },
        ),
        migrations.AddIndex(
            model_name='recurringworkitem',
            index=models.Index(fields=['project', 'is_active', 'next_run_at'], name='recurring_w_project_ffff9c_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringworkitem',
            index=models.Index(fields=['project', 'template'], name='recurring_w_project_ad01f4_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringworkitemrun',
            index=models.Index(fields=['project', 'run_at'], name='recurring_w_project_dbd4ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringworkitemrun',
            constraint=models.UniqueConstraint(fields=('recurring_work_item', 'run_at'), name='unique_recurring_work_item_run_at'),
        ),
    ]
