# Generated by Django 5.2.15 on 2026-06-14 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_recurring_work_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueproperty',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issueproperty',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issueproperty',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issueproperty',
            name='is_multi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuepropertyvalue',
            name='value_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuepropertyvalue',
            name='value_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issueproperty',
            name='property_type',
            field=models.CharField(choices=[('text', 'Text'), ('option', 'Option'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('boolean', 'Boolean'), ('member', 'Member'), ('url', 'URL')], max_length=32),
        ),
        migrations.CreateModel(
            name='IssuePropertyOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.FloatField(default=65535)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='db.issueproperty')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Issue Property Option',
                'verbose_name_plural': 'Issue Property Options',
                'db_table': 'issue_property_options',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='issuepropertyvalue',
            name='value_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='db.issuepropertyoption'),
        ),
    ]
