# Generated by Django 5.2.15 on 2026-06-14 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0131_initiatives"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusUpdate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ON_TRACK", "On Track"),
                            ("AT_RISK", "At Risk"),
                            ("OFF_TRACK", "Off Track"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment_stripped", models.TextField(blank=True, verbose_name="Comment")),
                ("comment_json", models.JSONField(blank=True, default=dict)),
                ("comment_html", models.TextField(blank=True, default="<p></p>")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "epic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="db.issue",
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="db.initiative",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="db.statusupdate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Update",
                "verbose_name_plural": "Status Updates",
                "db_table": "status_updates",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="StatusUpdateReaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reaction", models.TextField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_update_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "status_update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="db.statusupdate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Update Reaction",
                "verbose_name_plural": "Status Update Reactions",
                "db_table": "status_update_reactions",
                "ordering": ("-created_at",),
                "unique_together": {("status_update", "actor", "reaction", "deleted_at")},
            },
        ),
        migrations.AddConstraint(
            model_name="statusupdatereaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("status_update", "actor", "reaction"),
                name="status_update_reaction_unique_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="statusupdate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("epic__isnull", False), ("initiative__isnull", True)),
                    models.Q(("epic__isnull", True), ("initiative__isnull", False)),
                    _connector="OR",
                ),
                name="status_update_epic_xor_initiative",
            ),
        ),
    ]
