# Generated by Django 5.2.15 on 2026-06-23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0132_status_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description_json", models.JSONField(blank=True, default=dict)),
                ("description_binary", models.BinaryField(blank=True, null=True)),
                ("description_html", models.TextField(blank=True, default="<p></p>")),
                ("description_stripped", models.TextField(blank=True, null=True)),
                ("logo_props", models.JSONField(blank=True, default=dict)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("meeting_notes", "Meeting Notes"),
                            ("runbook", "Runbook"),
                            ("charter", "Charter"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=30,
                    ),
                ),
                (
                    "access",
                    models.PositiveSmallIntegerField(choices=[(1, "Private"), (0, "Public")], default=0),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_templates",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_templates",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Template",
                "verbose_name_plural": "Page Templates",
                "db_table": "page_templates",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["workspace", "project", "access"], name="page_templa_workspa_738b3d_idx"),
                    models.Index(fields=["workspace", "owned_by"], name="page_templa_workspa_9089d0_idx"),
                ],
            },
        ),
    ]
