# Generated by Django 5.2.15 on 2026-06-23

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0133_page_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueEmbedding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("model_name", models.CharField(max_length=120)),
                ("provider", models.CharField(blank=True, default="", max_length=60)),
                ("embedding", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("ready", "Ready"), ("skipped", "Skipped"), ("failed", "Failed")],
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("embedded_at", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="db.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Embedding",
                "verbose_name_plural": "Issue Embeddings",
                "db_table": "issue_embeddings",
            },
        ),
        migrations.AddConstraint(
            model_name="issueembedding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("workspace", "project", "issue", "model_name"),
                name="issue_embedding_unique_active_model",
            ),
        ),
        migrations.AddIndex(
            model_name="issueembedding",
            index=models.Index(fields=["workspace", "project", "model_name"], name="issue_embed_workspa_121e46_idx"),
        ),
        migrations.AddIndex(
            model_name="issueembedding",
            index=models.Index(fields=["issue", "content_hash"], name="issue_embed_issue_i_986c59_idx"),
        ),
    ]
