# Generated by Django 5.2.15 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0135_ai_summaries"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisummary",
            name="share_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
