# Generated by Django 5.2.15 on 2026-06-24 15:34

import plane.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0137_ai_automation_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackprojectsync',
            name='signing_secret',
            field=plane.db.fields.SecretField(blank=True, default=''),
        ),
    ]
